exclude: 'docs|node_modules|migrations|.git|.tox'
default_stages: [commit]
fail_fast: false

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: end-of-file-fixer
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: detect-aws-credentials
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: detect-private-key
        files: (^|/)a/.+\.(py|html|sh|css|js)$
      - id: trailing-whitespace
        files: (^|/)a/.+\.(html|sh|css|js)$
      - id: no-commit-to-branch
        args: [--branch, staging, --branch, master]
      - id: fix-encoding-pragma
        args: []


# Additional 3rd party hooks
-   repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
      - id: bandit
        name: bandit
        entry: bandit
        args: ["--exclude", "/tests/, local.py,"]
        language: python
        types: [python]
      - id: isort
        name: isort (python)
        entry: isort
        args: ["--profile", "black"]
        language: python
        types: [python]